language: python

sudo: false

python:
  - "2.7"
  - "3.6"

install:
  - pip install --upgrade pip setuptools wheel
  - pip install --only-binary=numpy, scipy
  - python setup.py install

script:
  - python setup.py test

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: PYPI_USERNAME
  password:
    secure: HASHED_PASSWORD (READ DOCS ON TRAVIS CI)
  on:
    tags: true
    repo:
    python: 
